package UserInteractABR.FriendPlaylistInteractABR;

import UserInteractABR.UserInteractRequestModel;

public interface CheckFriendPlaylistInputBoundary {
    public CheckFriendPlaylistResponseModel reactTo(UserInteractRequestModel checkFriendPlaylistRequestModelRequestModel);
}
