name: GitHub Classroom Workflow v2

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
      
    name: Autograding
    steps:
      - uses: supercharge/mongodb-github-action@1.8.0 
      - with:
          mongodb-username: root
          mongodb-password: rootpassword
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
